#!venv/bin/python3.7

import re
import sys

print("checking password '{}'".format(sys.argv[1]))
result = False
with open('data.txt', 'r') as file:
    for line in file:
        if re.search(sys.argv[1], line):
            result = True
            break
    if result:
        print('Common password')
    else:
        print('Not common password')